"""Backend-neutral repository contracts for authoritative Raggy data."""
from __future__ import annotations

from typing import Any, Protocol


class SessionRepository(Protocol):
    def create_session(self, title: str = "New chat", project_scope: str | None = None,
                       project_id: str | None = None, owner_id: str = "default") -> dict: ...
    def get_session(self, session_id: str, owner_id: str = "default") -> dict | None: ...
    def list_sessions(self, owner_id: str = "default") -> list[dict]: ...
    def update_project_scope(self, session_id: str, project_scope: str | None,
                             project_id: str | None = None, owner_id: str = "default") -> dict: ...
    def append_message(self, session_id: str, role: str, content: str,
                       attachments: list[dict] | None = None, trace_id: str | None = None,
                       owner_id: str = "default") -> str: ...
    def get_messages(self, session_id: str, owner_id: str = "default") -> list[dict]: ...
    def create_project(self, name: str, owner_id: str = "default") -> dict: ...
    def get_project(self, project_id: str, owner_id: str = "default") -> dict | None: ...
    def list_projects(self, owner_id: str = "default") -> list[dict]: ...
    def project_name_mapping(self) -> dict[tuple[str, str], dict]: ...


class MemoryRepository(Protocol):
    def get(self, memory_id: str) -> Any: ...
    def list(self, **filters: Any) -> list[Any]: ...
    def upsert(self, record: Any, **kwargs: Any) -> None: ...
    def capture_event(self, record: Any, **kwargs: Any) -> Any: ...
    def expire_due(self, **kwargs: Any) -> list[Any]: ...
    def backfill_project_ids(self, projects: dict[tuple[str, str], dict]) -> dict[str, int]: ...
    def claim_projection_jobs(self, *, limit: int = 50) -> list[dict]: ...


class EvidenceRepository(Protocol):
    def upsert_asset(self, asset: Any) -> None: ...
    def upsert_evidence(self, segments: list[Any]) -> None: ...
    def get_evidence(self, evidence_id: str, **filters: Any) -> Any: ...
    def start_ingestion(self, asset_id: str, **kwargs: Any) -> dict: ...
    def complete_ingestion(self, run_id: str, **kwargs: Any) -> None: ...
    def get_document_status(self, asset_id: str, **kwargs: Any) -> dict | None: ...


class GraphRepository(Protocol):
    def sync_memory(self, record: Any) -> None: ...
    def list_nodes(self, **filters: Any) -> list[dict]: ...
    def list_edges(self, **filters: Any) -> list[dict]: ...
